namespace Pure.DI.Core;

static class LogMetadata
{
    public static string GetCategory(string id) =>
        id switch
        {
            LogId.ErrorInvalidBinding => "Bindings",
            LogId.ErrorInvalidBindingDueToCompilation => "Bindings",
            LogId.ErrorInvalidArgumentName => "Bindings",
            LogId.ErrorCompositionArgGenericMarker => "Bindings",
            LogId.ErrorAccumulatorTypeGenericMarker => "Bindings",
            LogId.ErrorAccumulatorCannotAccumulateGenericMarker => "Bindings",
            LogId.ErrorSpecialTypeGenericMarker => "Bindings",
            LogId.ErrorNotImplementedContract => "Bindings",
            LogId.WarningNotImplementedContract => "Bindings",
            LogId.InfoNotImplementedContract => "Bindings",
            LogId.WarningBindingNotUsed => "Bindings",
            LogId.WarningOverriddenBinding => "Bindings",

            LogId.ErrorInvalidCompositionTypeName => "Setup",
            LogId.ErrorInvalidRootName => "Setup",
            LogId.ErrorDuplicateRootName => "Setup",
            LogId.ErrorInvalidRootType => "Setup",
            LogId.ErrorInvalidRootsType => "Setup",
            LogId.ErrorNoTypeForWildcard => "Setup",
            LogId.ErrorInvalidBuildersType => "Setup",
            LogId.ErrorInvalidBuilderType => "Setup",
            LogId.ErrorCannotFindSetup => "Setup",
            LogId.WarningNoRoots => "Setup",
            LogId.WarningRootArgInResolveMethod => "Setup",
            LogId.WarningTypeArgInResolveMethod => "Setup",
            LogId.WarningInstanceMemberInDependsOnSetup => "Setup",

            LogId.ErrorAsyncFactoryNotSupported => "Factories",
            LogId.ErrorCannotUseContextDirectly => "Factories",
            LogId.ErrorInvalidNumberOfInitializers => "Factories",
            LogId.ErrorLifetimeDoesNotSupportCyclicDependencies => "Factories",

            LogId.ErrorUnableToResolve => "Validation",
            LogId.ErrorCyclicDependency => "Validation",
            LogId.ErrorTooLargeComposition => "Validation",
            LogId.ErrorCannotConstructAbstractType => "Validation",
            LogId.ErrorNoAccessibleConstructor => "Validation",
            LogId.ErrorCannotBuildDependencyGraph => "Validation",
            LogId.ErrorMaximumNumberOfIterations => "Validation",
            LogId.ErrorNoAccessibleConstructorForTagOn => "Validation",
            LogId.ErrorNoAccessibleMethodForTagOn => "Validation",
            LogId.ErrorNoAccessibleFieldOrPropertyForTagOn => "Validation",
            LogId.ErrorMustBeApiCall => "Validation",
            LogId.ErrorMustBeValueOfType => "Validation",
            LogId.ErrorInvalidIdentifier => "Validation",
            LogId.ErrorInvalidRegularExpression => "Validation",
            LogId.ErrorInvalidWildcard => "Validation",
            LogId.ErrorTooManyTypeParameters => "Validation",
            LogId.ErrorNotSupportedSyntax => "Validation",
            LogId.ErrorNotSupportedLanguageVersion => "Validation",
            LogId.ErrorLifetimeDefect => "Validation",
            LogId.ErrorTypeCannotBeInferred => "Validation",
            LogId.ErrorInvalidAttributeArgumentPosition => "Validation",
            LogId.ErrorAttributeMemberCannotBeProcessed => "Validation",
            LogId.WarningInjectionSiteNotUsed => "Validation",

            LogId.InfoGenerationInterrupted => "General",
            LogId.ErrorUnhandled => "General",
            _ => "General"
        };

    public static string? GetDescription(string id) =>
        id switch
        {
            LogId.ErrorUnableToResolve => Strings.Description_ErrorUnableToResolve,
            LogId.ErrorInvalidBinding => Strings.Description_ErrorInvalidBinding,
            LogId.ErrorInvalidBindingDueToCompilation => Strings.Description_ErrorInvalidBindingDueToCompilation,
            LogId.ErrorInvalidCompositionTypeName => Strings.Description_ErrorInvalidCompositionTypeName,
            LogId.ErrorInvalidRootName => Strings.Description_ErrorInvalidRootName,
            LogId.ErrorDuplicateRootName => Strings.Description_ErrorDuplicateRootName,
            LogId.ErrorInvalidArgumentName => Strings.Description_ErrorInvalidArgumentName,
            LogId.ErrorCompositionArgGenericMarker => Strings.Description_ErrorCompositionArgGenericMarker,
            LogId.ErrorAccumulatorTypeGenericMarker => Strings.Description_ErrorAccumulatorTypeGenericMarker,
            LogId.ErrorAccumulatorCannotAccumulateGenericMarker => Strings.Description_ErrorAccumulatorCannotAccumulateGenericMarker,
            LogId.ErrorSpecialTypeGenericMarker => Strings.Description_ErrorSpecialTypeGenericMarker,
            LogId.ErrorNotImplementedContract => Strings.Description_ErrorNotImplementedContract,
            LogId.ErrorInvalidAttributeArgumentPosition => Strings.Description_ErrorInvalidAttributeArgumentPosition,
            LogId.ErrorAttributeMemberCannotBeProcessed => Strings.Description_ErrorAttributeMemberCannotBeProcessed,
            LogId.ErrorInvalidRootType => Strings.Description_ErrorInvalidRootType,
            LogId.ErrorInvalidRootsType => Strings.Description_ErrorInvalidRootsType,
            LogId.ErrorNoTypeForWildcard => Strings.Description_ErrorNoTypeForWildcard,
            LogId.ErrorInvalidBuildersType => Strings.Description_ErrorInvalidBuildersType,
            LogId.ErrorInvalidBuilderType => Strings.Description_ErrorInvalidBuilderType,
            LogId.ErrorTooManyTypeParameters => Strings.Description_ErrorTooManyTypeParameters,
            LogId.ErrorAsyncFactoryNotSupported => Strings.Description_ErrorAsyncFactoryNotSupported,
            LogId.ErrorNotSupportedSyntax => Strings.Description_ErrorNotSupportedSyntax,
            LogId.ErrorMustBeValueOfType => Strings.Description_ErrorMustBeValueOfType,
            LogId.ErrorInvalidIdentifier => Strings.Description_ErrorInvalidIdentifier,
            LogId.ErrorCannotUseContextDirectly => Strings.Description_ErrorCannotUseContextDirectly,
            LogId.ErrorInvalidNumberOfInitializers => Strings.Description_ErrorInvalidNumberOfInitializers,
            LogId.ErrorLifetimeDoesNotSupportCyclicDependencies => Strings.Description_ErrorLifetimeDoesNotSupportCyclicDependencies,
            LogId.ErrorTooLargeComposition => Strings.Description_ErrorTooLargeComposition,
            LogId.ErrorCannotConstructAbstractType => Strings.Description_ErrorCannotConstructAbstractType,
            LogId.ErrorNoAccessibleConstructor => Strings.Description_ErrorNoAccessibleConstructor,
            LogId.ErrorCannotBuildDependencyGraph => Strings.Description_ErrorCannotBuildDependencyGraph,
            LogId.ErrorMaximumNumberOfIterations => Strings.Description_ErrorMaximumNumberOfIterations,
            LogId.ErrorNoAccessibleConstructorForTagOn => Strings.Description_ErrorNoAccessibleConstructorForTagOn,
            LogId.ErrorNoAccessibleMethodForTagOn => Strings.Description_ErrorNoAccessibleMethodForTagOn,
            LogId.ErrorNoAccessibleFieldOrPropertyForTagOn => Strings.Description_ErrorNoAccessibleFieldOrPropertyForTagOn,
            LogId.ErrorMustBeApiCall => Strings.Description_ErrorMustBeApiCall,
            LogId.ErrorInvalidRegularExpression => Strings.Description_ErrorInvalidRegularExpression,
            LogId.ErrorInvalidWildcard => Strings.Description_ErrorInvalidWildcard,
            LogId.ErrorCannotFindSetup => Strings.Description_ErrorCannotFindSetup,
            LogId.ErrorCyclicDependency => Strings.Description_ErrorCyclicDependency,
            LogId.ErrorNotSupportedLanguageVersion => Strings.Description_ErrorNotSupportedLanguageVersion,
            LogId.ErrorLifetimeDefect => Strings.Description_ErrorLifetimeDefect,
            LogId.ErrorTypeCannotBeInferred => Strings.Description_ErrorTypeCannotBeInferred,
            LogId.WarningOverriddenBinding => Strings.Description_WarningOverriddenBinding,
            LogId.WarningNoRoots => Strings.Description_WarningNoRoots,
            LogId.WarningNotImplementedContract => Strings.Description_WarningNotImplementedContract,
            LogId.WarningBindingNotUsed => Strings.Description_WarningBindingNotUsed,
            LogId.WarningInjectionSiteNotUsed => Strings.Description_WarningInjectionSiteNotUsed,
            LogId.WarningRootArgInResolveMethod => Strings.Description_WarningRootArgInResolveMethod,
            LogId.WarningTypeArgInResolveMethod => Strings.Description_WarningTypeArgInResolveMethod,
            LogId.WarningInstanceMemberInDependsOnSetup => Strings.Description_WarningInstanceMemberInDependsOnSetup,
            LogId.InfoGenerationInterrupted => Strings.Description_InfoGenerationInterrupted,
            LogId.InfoNotImplementedContract => Strings.Description_InfoNotImplementedContract,
            LogId.ErrorUnhandled => Strings.Description_ErrorUnhandled,
            _ => null
        };
}
