namespace Pure.DI.Core.Code.Parts;

class FileHeader(IInformation information) : IFileHeader
{
    public void Add(Compilation compilation, Lines code)
    {
        _ = compilation;
        code.AppendComments("<auto-generated/>", $"by {information.Description}");
        code.AppendLine("#nullable enable annotations");
    }
}
